config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  resources :posts  do
   resources :answers, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :post
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :post_id,presence:true
  validates :name,presence:true,length:{maximum:50}
  validates :comment,presence:true,length:{maximum: 255}
  
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_one_attached :image 
  default_scope->{order(created_at: :desc)}
  validates:title,presence:true,length:{maximum:50}
  validates:content,presence:true,length:{maximum:255}
  validates:image, content_type:{in:%w[image/jpeg image/gif image/png],
                    message:"must be avalid image formaat"},
            size:{less_than:5.megabytes,
                    message:"should be less than 5MB"}
                    
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
                    
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @answer = Answer.new
    @answer_image = @post.answers.build.image.attach(params[:answer][:image])
    
    if @answer.update(answer_params) && @answer_image.save
      flash[:success] = "Answer created!"
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end
  
  def destroy
    @post = Post.find(params[:post_id])  
    @answer=@post.answers.find(params[:id])
    @answer.destroy
    
    flash[:success] = "Answer deleted"
    redirect_to request.referrer || post_answer_url
  end
  
  private

  def answer_params
    params.require(:answer).permit(:name,:comment,:image,:post_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success]="投稿しました"
      redirect_to posts_url
    else
      render 'new'
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @answer = Answer.new
    @answers = @post.answers.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post updated"
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  
  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to @post
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title,:content,:image)
  end
  
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/_footer.html.erb
<section class="footer">
    <p>tetete知恵袋 @ 2020 tetetearraio916
    created_at_2020_8_12 . </p>
</section>

app/views/layouts/_header.html.erb
<header class="nav-down responsive-nav hidden-lg hidden-md">
    <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <!--/.navbar-header-->
    <div id="main-nav" class="collapse navbar-collapse">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Home",root_path %></li>
                <li><%= link_to "Index",posts_path %></li>
                <li><%= link_to "New",new_post_path %></li>
            </ul>
        </nav>
    </div>
</header>
<div class="sidebar-navigation hidde-sm hidden-xs">
    <div class="logo">
        <a href="#">tetete<em>＠知恵袋</em></a>
    </div>
    <nav>
        <ul>
            <li>
                <%= link_to root_path do %>
                    <span class="rect"></span>
                    <span class="circle"></span>
                    Home
                <% end %>
            </li>
            <li>
                <%= link_to posts_path do %>
                    <span class="rect"></span>
                    <span class="circle"></span>
                    Question Posts
                <% end %>
            </li>
            <li>
                <%= link_to new_post_path do %>
                    <span class="rect"></span>
                    <span class="circle"></span>
                    Let's ask
                <% end %>
            </li>
        </ul>
    </nav>
    <ul class="social-icons">
        <li>
            <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Ftetetearraio916-portfolio1.herokuapp.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">
            <i class="fa fa-facebook" data-href="https://d924a5bf45a8441eba5b6ab8031669bd.vfs.cloud9.ap-northeast-1.amazonaws.com/" data-layout="button_count" data-size="small"></i>
            </a>
        </li>
        <li>
            <%= link_to "http://twitter.com/share?url=#{(root_url)}/&text=わからないことをなくそう！/&hashtags=tetete知恵袋" do %>
                <i class="fa fa-twitter"></i>
            <% end %>
        </li>
        <li>
            <%= link_to "https://social-plugins.line.me/lineit/share?url=#{(root_url)}/&text=わからないことをなくそう！&hashtags=TETETE知恵袋" do %>
                <i class="fab fa-line"></i>
            <% end %>
        </li>    
    </ul>    
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v8.0" nonce="2Hl34KLY"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %>  TETETE@知恵袋</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="page-content">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>   
      </div>
      <%= render 'layouts/footer' %>
  </body>    
</html>

app/views/posts/edit.html.erb
<% provide(:title, "") %>
<section id="contact" class="content-section">
    <div id="contact-content">
            <div class="section-heading">
                <h1>Edit<br><em>Page</em></h1>
            </div>
            <div class = "row">
                <aside class = "col-md-10">
                    <section class = "post_form">
                        <%= render 'shared/post_form' %>
                    </section>
                </aside>
            </div>
    </div>
</section>     

app/views/posts/index.html.erb
<% provide(:title, "Question Posts") %>
<section id="blog" class="content-section">
    <div class="section-heading">
        <h1>Question<br><em>Posts</em></h1>
        <p>興味のあるトピックがあるかもしれません。
        <br>あなたに助力できることを私たちは願っています。</p>
    </div>
    <div class="section-content">
        <div class="tabs-content">
            <div class="wrapper">
                <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
                <ul class="tabs clearfix" data-tabgroup="first-tab-group">
                    <li><a href="#tab1" class="active">August 2020</a></li>
                    <li><a href="#tab2">July 2020</a></li>
                    <li><a href="#tab3">June 2020</a></li>
                    <li><a href="#tab4">May 2020</a></li>
                </ul>   
                
                <% if @posts.any? %>
                    <h4>Number of posts　<%= @posts.count %> </h4>
                    <ol class="posts">
                        <%= render 'shared/post' %>
                    </ol>
                <% end %>
              <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>   
            </div>
        </div>
    </div>
</section>
         

app/views/posts/new.html.erb
<% provide(:title, "Let's Ask!") %>
<section id="contact" class="content-section">
    <div id="contact-content">
        <div class="section-heading">
            <h1>Let's<br><em>ask a question!</em></h1>
            <p>投稿してみましょう。
            <br>わからないこと、悩んでいること、一緒に解決しましょう！</p>        
        </div>
        <div class="section-content">
            <div class="row"> 
                <%= render 'shared/post_form' %> 
            </div>
        </div>
    </div>
</section>            
          

app/views/posts/show.html.erb
<% provide(:title, "Question and Answers") %>
<section id="blog" class="content-section">
    <div class="section-content">
        <div class="tabs-content">
            <div class="wrapper">
                <ol class="posts">
                    <%= render 'shared/post_show' %>
                </ol>
            </div>
        </div>
    </div>    

    <div class="section-content">
        <div class="tabs-content">
            <div class="wrapper">
                <%= will_paginate @answers, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>   
                <ul class="tabs clearfix" data-tabgroup="first-tab-group">
                    <li><a href="#tab1" class="active">August 2020</a></li>
                    <li><a href="#tab2">July 2020</a></li>
                    <li><a href="#tab3">June 2020</a></li>
                    <li><a href="#tab4">May 2020</a></li>
                </ul>   
                
                <% if @post.answers.any? %>
                    <h4>Number of answers　<%= @post.answers.count %> </h4>
                    <ol class="posts">
                        <%= render 'shared/answer' %>
                    </ol>
                <% end %>
                <%= will_paginate @answers, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>   
            </div>
        </div>
    </div>
</section>

<section id="contact" class="content-section">
    <div id="contact-content">
        <div class="section-heading">
            <h1>Please<br><em>Answers</em></h1>
            <p>親切なあなたへ
            <br>あなたの行動に私たちは感謝しています。</p>        
        </div>
        <div class="section-content">
            <div class="row"> 
                <%= render 'shared/answer_form' %> 
            </div>
        </div>
    </div>
</section>            

app/views/shared/_answer.html.erb
<section id="first-tab-group" class="tabgroup">
    <% @post.answers.each do |answer| %>
        <div id="tab1">
            <ul>
                <li>
                    <div class="item">
                        <div class="text-content">
                            <div class="col-md-12">
                                <h4><%= answer.name %></h4>
                                <span><%= answer.comment %></span>
                            </div>
                            <div class="col-md-4">
                                 <%= image_tag answer.display_image if answer.image.attached? %>
                            </div>
                            <div class="col-md-12">
                                <p>Posted <%= time_ago_in_words(answer.created_at) if answer.created_at %> ago.
                                <%= answer.created_at %></p>
                                <div class="accent-button button">
                                    <ul>
                                        <li><%= button_to "delete",post_answer_path(@post,answer), method: :delete, data: { confirm: "You sure?" },class: "accent-button button" %></li>
                                    </ul>           
                                </div>
                            </div>
                        </div>
                    </div>
                </li>                        
            </ul>
        </div>
    <% end %>
</section> 

app/views/shared/_answer_form.html.erb
<%= form_with model: [@post,@answer], local: true do |f| %>
  <%= render 'shared/error_messages',object: f.object %> 
  <%= f.hidden_field :post_id,{value:@post.id} %>
  
      <fieldset>
        
        <div class="col-md-1">
          <%= f.label :name %>
        </div>
        <div class="col-md-12">
          <%= f.text_field :name, placeholder: "Compose new name..." %>
        </div>
      </fieldset>
                                
      <fieldset>
        <div class="col-md-1">
          <%= f.label :comment %>
        </div>
        <div class="col-md-12">
          <%= f.text_area :comment, placeholder: "Compose new answer..." %>
        </div>
      </fieldset>
      
      <fieldset>                                                   
        <div class="col-md-12">                               
          <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %> 
        </div>
        <div class="col-md-5">
        </div>
        <div class="col-md-2">
          <button type="submit" id="form-submit" class="btn">Answered Now</button>
        </div>
      </fieldset>
<% end %>


                
<script type="text/javascript">
  $("#answer_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#answer_image").val("");
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post.html.erb
<section id="first-tab-group" class="tabgroup">
    <% @posts.each do |post| %>
        <div id="tab1">
            <ul>
                <li>
                    <div class="item">
                        <div class="text-content">
                            <div class="col-md-12">
                                <h4><%= link_to post.title,post_path(post) %></h4>
                                <span><%= post.content %></span>
                            </div>
                            <div class="col-md-4">
                                <%= image_tag post.display_image if post.image.attached? %>
                            </div>
                            <div class="col-md-12">
                                <p>Posted <%= time_ago_in_words(post.created_at) %> ago.
                                    <%= post.created_at %></p>
                                <div class="accent-button button">
                                    <ul>
                                        <li><%= link_to "Settings",edit_post_path(post) %> </li>
                                        <li><%= button_to "delete", post_path(post.id), method: :delete, data: { confirm: "You sure?" } %></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>                        
            </ul>
        </div>
    <% end %>
</section> 

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages',object: f.object %>                         
      <fieldset>
        <div class="col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-12">
          <%= f.text_field :title, placeholder: "Compose new title..." %>
        </div>
      </fieldset>
                                
      <fieldset>
        <div class="col-md-1">
          <%= f.label :post %>
        </div>
        <div class="col-md-12">
          <%= f.text_area :content, placeholder: "Compose new post..." %>
        </div>
      </fieldset>
      
      <fieldset>                                                   
        <div class="col-md-12">                               
          <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %> 
        </div>
        <div class="col-md-5">
        </div>
        <div class="col-md-2">
          <button type="submit" id="form-submit" class="btn">Posted Now</button>
        </div>
      </fieldset>
<% end %>
                
<script type="text/javascript">
  $("#post_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#post_image").val("");
    }
  });
</script>
    

app/views/shared/_post_show.html.erb
<section id="first-tab-group" class="tabgroup">
    <div id="tab1">
        <div class="item">
          <%= image_tag @post.display_image if @post.image.attached? %>
            <div class="text-content">
                    <h4><%= @post.title %></h4>
                    <span><%= @post.content %></span>
            </div>
        </div>
    </div>
</section> 

app/views/staticpages/home.html.erb
<div class="slider">
    <div class="Modern-Slider content-section" id="top">
        <!-- Item -->
        <div class="item item-1">
            <div class="img-fill">
                <div class="image">
                    <%= image_tag 'slide_1.jpg' %>
                </div>
                <div class="info">
                    <div>
                    <h1>Ask questions<br>if you don't understand</h1>
                    <p>わからない事、悩み、人と共有したい事がそれぞれあると思います。<br>
                       あなたの抱えている問題がここで解決できるよう私たちが全力でサポートします。</p>
                    <div class="white-button button">
                            <%= link_to posts_path do %>
                              Questions
                            <% end %>
                            <%= link_to new_post_path do %>
                                 Let's ask !
                            <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                